services:
  blog-app:
    image: staffolis/golb:latest
    container_name: go_blog
    restart: unless-stopped
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    container_name: blog_nginx
    restart: unless-stopped
    ports:
      - "8090:80"
    depends_on:
      - blog-app
    volumes:
      - static:/usr/share/nginx/html:ro
      - <PATH-TO-THE-CONF-ON-THE-NAS>/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cf_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token <TOKEN-HERE-FIX-ME>

volumes:
  static:
    external: true
