services:
  blog-app:
    build: .
    container_name: go_blog
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates

  nginx:
    image: nginx:alpine
    container_name: blog_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro 
    depends_on:
      - blog-app
